language: rust
cache: cargo

matrix:
  include:
  - rust: 1.37.0
    env: NAME=test
    before_script:
    - rustup component add rustfmt
    script:
    - cargo test --all --verbose
  - rust: 1.37.0
    env: NAME=pretty
    before_script:
    - rustup component add rustfmt
    script:
    - cargo fmt -- --check
  - rust: 1.37.0
    env: NAME=petty
    before_script:
    - rustup component add clippy
    script:
    - cargo clippy --all --verbose

notifications:
  email:
    on_success: never
