[package]
name = "fusebox"
version = "0.1.0"
authors = ["Brendan Molloy <brendan@bbqsrc.net>"]
edition = "2018"

[dependencies]
fuser = { git = "https://github.com/cberner/fuser" }
structopt = "0.3.17"
box-format = { path = "../box-format" }
env_logger = "0.9"
libc = "0.2.76"
log = "0.4.11"
